import { ContextProvider } from "../../context/contextProvider";
import "./globals.css";

export const metadata = {
  title: "وبسایت شخصی | محمد پورحسین",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" dir="rtl">
      <body>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}